name: Test & Deploy

on:
  push:
    branches:
      - test-actions

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test   # Ensures this job only runs after the test job completes successfully
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.toml --dockerfile Dockerfile
        working-directory: src
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
