name: Fly Deploy
on:
  push:
    branches:
      - fly
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.toml --dockerfile Dockerfile
        working-directory: src
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
